version: '3.4'

services:
  mutate-mammals-validator:
    image: localhost:5000/mutate-mammals-validator:1.0.0
    build:
      context: ./validator
    ports:
      - 5000:5001
    volumes:
      - .:/app
    environment:
      ENVIRONMENT: dev
      VALIDATOR_PORT: 5001
      APP_HOST: mutate-mammals-service
      APP_PORT: 5000

  mutate-mammals-service:
    image: localhost:5000/mutate-mammals-service:1.0.0
    build:
      context: ./app
    command: flask --app ./app/main.py --debug run --host 0.0.0.0
    ports:
      - 5001:5000
    volumes:
      - .:/app
    environment:
      ENVIRONMENT: dev
      MAMMALS_MONGO_CONN_STRING: mongodb://mammals-mongo:27017

  mammals-mongo:
    image: heinvde.mammals/mongo:1.0.0
    command: mongod --quiet --logpath /dev/null
