version: '3.4'

services:
  mammals-graphql-api:
    image: heinvde.tinybackpack/graphql-api:1.0.0
    build: .
    command: pm2-runtime start ecosystem.config.js --no-auto-exit
    environment:
      QUERY_MAMMALS_SERVICE_HOST: http://query-mammals-service:5000
      MUTATE_MAMMALS_SERVICE_HOST: http://mutate-mammals-validator:5001
    ports:
      - 8077:8077
    volumes:
      - .:/usr/app

  query-mammals-service:
    image: heinvde.mammals/query-mammals-service:1.0.0
    environment:
      ENVIRONMENT: dev
      MAMMALS_MONGO_CONN_STRING: mongodb://mammals-mongo:27017

  mutate-mammals-validator:
    image: heinvde.mammals/mutate-mammals-validator:1.0.0
    environment:
      ENVIRONMENT: dev
      VALIDATOR_PORT: 5001
      APP_HOST: mutate-mammals-service
      APP_PORT: 5000

  mutate-mammals-service:
    image: heinvde.mammals/mutate-mammals-service:1.0.0
    environment:
      ENVIRONMENT: dev
      MAMMALS_MONGO_CONN_STRING: mongodb://mammals-mongo:27017

  mammals-mongo:
    image: heinvde.mammals/mongo:1.0.0
    command: mongod --quiet --logpath /dev/null
